#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <queue>
#include <thread>
#include <mutex>
#include <chrono>
#include <random>
#include <cmath>
#include <iomanip>
#include <string>
#include <atomic>
#include <algorithm> // Added for std::max, std::min_element, std::max_element

// Define the two scheduler types
enum class SchedulerType { FCFS, WFQ };

/**
 * @brief Represents a single packet generated by a source.
 */
struct Packet {
    long long id;
    int source_id;
    int size; // Packet size in bits
    std::chrono::steady_clock::time_point generation_time;
    double finish_number; // Used only for WFQ scheduling
};

// Removed ComparePacketFinishTime struct as we are switching to std::vector for WFQ queue

/**
 * @brief Defines the characteristics of a single traffic source.
 */
struct Source {
    int id;
    double packet_rate; // Packets per second (lambda for exponential distribution)
    int l_min, l_max; // Packet size range in bits
    double weight; // Weight (w_i) for WFQ
    double start_time, end_time; // Absolute active duration in seconds
};

// --- Global Simulation Parameters ---
int N_SOURCES;
double SIM_DURATION_T;
double LINK_CAPACITY_C; // bits per second
int BUFFER_SIZE_B; // number of packets
std::vector<Source> sources;

// --- Shared Resources for Concurrency ---
std::mutex queue_mutex;
std::queue<Packet> shared_queue_fcfs;
// Using std::vector instead of std::priority_queue for WFQ to enable LFTD (Largest Finish Time Drop)
std::vector<Packet> shared_queue_wfq; 

std::atomic<bool> simulation_running{false};
std::chrono::steady_clock::time_point global_start_time;

// --- WFQ State Variables ---
double virtual_time = 0.0;
// Finish time of the last packet from each source (L_i)
std::vector<double> last_finish_time;

// --- Global Metrics ---
std::atomic<long long> total_packets_generated{0};
std::atomic<long long> total_packets_dropped{0};
long long total_packets_transmitted = 0;
long long total_bits_transmitted_global = 0;
double total_delay = 0.0; // Sum of all delays

// --- Per-source metrics ---
struct SourceMetrics {
    long long generated = 0;
    long long transmitted = 0;
    long long dropped = 0;
    long long bits_tx = 0;
    double delay_sum = 0.0;
};
std::vector<SourceMetrics> source_metrics;

/**
 * @brief Gets the current simulation time elapsed since global_start_time.
 * @return Current simulation time in seconds.
 */
double get_current_sim_time() {
    if (!simulation_running) return 0.0;
    return std::chrono::duration<double>(std::chrono::steady_clock::now() - global_start_time).count();
}

/**
 * @brief Thread function simulating an independent traffic source.
 */
void producer_thread(int source_id, SchedulerType type) {
    Source &src = sources[source_id];
    // Setup random number generators
    std::random_device rd;
    // Seed with source_id to ensure different sequences
    std::mt19937 gen(rd() + source_id);
    // Packet inter-arrival time is exponentially distributed (rate P_i)
    std::exponential_distribution<double> inter_arrival(src.packet_rate);
    // Packet size is uniformly distributed between L_min and L_max
    std::uniform_int_distribution<int> size_dist(src.l_min, src.l_max);
    long long packet_id = 0;

    while (simulation_running) {
        // Calculate and sleep for the inter-arrival time
        double sleep_time = inter_arrival(gen);
        std::this_thread::sleep_for(std::chrono::duration<double>(sleep_time));

        double current_time = get_current_sim_time();
        if (current_time > SIM_DURATION_T) break; // Check if simulation duration
        
        // Check if source is active at this time
        if (current_time < src.start_time || current_time > src.end_time) continue;

        Packet p;
        p.id = ((long long)source_id << 32) | packet_id++;
        p.source_id = source_id;
        p.size = size_dist(gen);
        p.generation_time = std::chrono::steady_clock::now();

        total_packets_generated++;
        source_metrics[source_id].generated++;

        std::lock_guard<std::mutex> lock(queue_mutex);
        if (type == SchedulerType::FCFS) {
            if (shared_queue_fcfs.size() < BUFFER_SIZE_B)
                shared_queue_fcfs.push(p);
            else {
                // FCFS drop: Buffer is full - drop new packet (tail drop)
                total_packets_dropped++;
                source_metrics[source_id].dropped++;
            }
        } else { // WFQ
            // S_i = max(V, L_i)
            double start_number = std::max(virtual_time, last_finish_time[source_id]);
            // F_i = S_i + P_i / w_i
            p.finish_number = start_number + (double)p.size / src.weight;
            
            if (shared_queue_wfq.size() < BUFFER_SIZE_B) {
                // Buffer has space - accept the packet
                last_finish_time[source_id] = p.finish_number;
                shared_queue_wfq.push_back(p);
            } else {
                // Buffer is full - implement Largest Finish Time Drop (LFTD)
                
                // 1. Find the packet currently in the queue with the LARGEST (worst) finish_number
                auto worst_it = std::max_element(shared_queue_wfq.begin(), shared_queue_wfq.end(), 
                    [](const Packet& a, const Packet& b) {
                        return a.finish_number < b.finish_number; 
                    });

                if (worst_it != shared_queue_wfq.end()) {
                    // 2. Check if the newly arriving packet is better (smaller finish time) than the worst queued packet
                    if (p.finish_number < worst_it->finish_number) {
                        // Drop the worst existing packet, and accept the new packet
                        
                        // Increment drop count for the source whose packet is being evicted
                        total_packets_dropped++;
                        source_metrics[worst_it->source_id].dropped++; 
                        
                        // Erase the worst packet (O(N) operation)
                        shared_queue_wfq.erase(worst_it);
                        
                        // Accept the new packet
                        last_finish_time[source_id] = p.finish_number;
                        shared_queue_wfq.push_back(p);
                    } else {
                        // The new packet is worse (or equal) than the worst already queued - drop the new packet
                        total_packets_dropped++;
                        source_metrics[source_id].dropped++;
                    }
                } else {
                    // Should theoretically not happen if size() >= BUFFER_SIZE_B, but drop new packet as fallback
                    total_packets_dropped++;
                    source_metrics[source_id].dropped++;
                }
            }
        }
    }
}

/**
 * @brief Thread function simulating the single output link (server).
 */
void server_thread(SchedulerType type) {
    // Continue processing as long as sim is running OR packets are left in the queue
    while (simulation_running ||
           (type == SchedulerType::FCFS && !shared_queue_fcfs.empty()) ||
           (type == SchedulerType::WFQ && !shared_queue_wfq.empty())) {
        
        Packet pkt;
        bool found = false;

        {
            std::lock_guard<std::mutex> lock(queue_mutex);
            if (type == SchedulerType::FCFS && !shared_queue_fcfs.empty()) {
                pkt = shared_queue_fcfs.front();
                shared_queue_fcfs.pop();
                found = true;
            } else if (type == SchedulerType::WFQ && !shared_queue_wfq.empty()) {
                // WFQ Scheduling: Find the packet with the SMALLEST finish_number
                auto best_it = std::min_element(shared_queue_wfq.begin(), shared_queue_wfq.end(), 
                    [](const Packet& a, const Packet& b) {
                        return a.finish_number < b.finish_number; 
                    });
                    
                pkt = *best_it;
                // Remove the scheduled packet (O(N) operation)
                shared_queue_wfq.erase(best_it);
                
                found = true;
                
                // Update virtual time
                // This is the theoretical finish time of the packet just starting service.
                virtual_time = std::max(virtual_time, pkt.finish_number);
            }
        }

        if (found) {
            // Calculate transmission time: size (bits) / capacity (bits/sec)
            double tx_time = (double)pkt.size / LINK_CAPACITY_C;
            
            // Simulate the transmission time by sleeping
            std::this_thread::sleep_for(std::chrono::duration<double>(tx_time));
            auto departure_time = std::chrono::steady_clock::now();
            
            // Calculate packet delay: (departure time - generation time)
            double delay = std::chrono::duration<double>(departure_time - pkt.generation_time).count();

            // --- Update Global Metrics ---
            total_delay += delay;
            total_packets_transmitted++;
            total_bits_transmitted_global += pkt.size;

            // --- Update Per-Source Metrics ---
            source_metrics[pkt.source_id].transmitted++;
            source_metrics[pkt.source_id].bits_tx += pkt.size;
            source_metrics[pkt.source_id].delay_sum += delay;
        } else if (simulation_running) {
            // If queue is empty but simulation is still running, sleep briefly
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        }
    }
}

/**
 * @brief Calculates Jain's Fairness Index based on per-source throughput and weight.
 * @return Fairness index (0 to 1)
 */
double calculate_fairness_index() {
    double sum_x = 0.0;    // Sum of (x_i)
    double sum_x_sq = 0.0; // Sum of (x_i^2)
    int active_sources = 0;

    for (int i = 0; i < N_SOURCES; ++i) {
        // Only consider sources that were active and transmitted data
        if (sources[i].weight > 0 && source_metrics[i].bits_tx > 0) {
            // x_i = (throughput_i / weight_i)
            double x_i = (double)source_metrics[i].bits_tx / sources[i].weight;
            sum_x += x_i;
            sum_x_sq += x_i * x_i;
            active_sources++;
        }
    }
    
    // If no active sources or denominator is zero, fairness is perfect
    if (active_sources <= 1 || sum_x_sq == 0) return 1.0;

    // Jain's Index: (Sum(x_i))^2 / (n * Sum(x_i^2))
    return (sum_x * sum_x) / (active_sources * sum_x_sq);
}

/**
 * @brief Parses the simulation parameters from the input file.
 * @param filename The name of the input file.
 * @return true if parsing succeeds, false otherwise.
 */
bool parse_input(const std::string &filename) {
    std::ifstream infile(filename);
    if (!infile.is_open()) {
        std::cerr << "Error: Could not open input file " << filename << std::endl;
        return false;
    }
    std::string line;

    // Parse the first line: N= T= C= B=
    if (std::getline(infile, line)) {
        std::stringstream ss(line);
        std::string temp;
        // Use `substr` and `find` to parse "key=value"
        ss >> temp; N_SOURCES = std::stoi(temp.substr(temp.find('=') + 1));
        ss >> temp; SIM_DURATION_T = std::stod(temp.substr(temp.find('=') + 1));
        ss >> temp; LINK_CAPACITY_C = std::stod(temp.substr(temp.find('=') + 1));
        ss >> temp; BUFFER_SIZE_B = std::stoi(temp.substr(temp.find('=') + 1));
    } else {
        return false; // Empty file
    }

    // Clear and resize global vectors
    sources.clear();
    last_finish_time.assign(N_SOURCES, 0.0);
    source_metrics.assign(N_SOURCES, {});

    // Parse N source lines
    for (int i = 0; i < N_SOURCES; ++i) {
        if (!std::getline(infile, line)) {
            std::cerr << "Error: Input file missing lines for all sources." << std::endl;
            return false;
        }
        std::stringstream ss(line);
        Source s;
        char comma; // To consume the comma between l_min and l_max
        ss >> s.packet_rate >> s.l_min >> comma >> s.l_max >> s.weight >> s.start_time >> s.end_time;
        
        // Scale start/end times (which are 0.0-1.0) by total duration
        s.start_time *= SIM_DURATION_T;
        s.end_time *= SIM_DURATION_T;
        s.id = i;
        sources.push_back(s);
    }
    return true;
}

/**
 * @brief Resets all global state variables and metrics for a new simulation run.
 */
void reset_globals() {
    // Clear the queues by swapping with empty ones
    std::queue<Packet> empty_fcfs; 
    std::swap(shared_queue_fcfs, empty_fcfs);
    
    std::vector<Packet> empty_wfq;
    std::swap(shared_queue_wfq, empty_wfq);

    virtual_time = 0.0;
    if (N_SOURCES > 0) {
        last_finish_time.assign(N_SOURCES, 0.0);
        source_metrics.assign(N_SOURCES, {});
    }
    
    // Reset atomic metrics
    total_packets_generated = 0;
    total_packets_dropped = 0;
    
    // Reset non-atomic metrics
    total_packets_transmitted = 0;
    total_bits_transmitted_global = 0;
    total_delay = 0.0;
}

/**
 * @brief Prints the detailed per-source statistics after a simulation run.
 * @param total_time The actual duration of the simulation.
 */
void print_per_source_stats(double total_time) {
    std::cout << "--- Per-Source Metrics ---\n";
    std::cout << "Src |  Gen  |  Tx   |  Drop |   BitsTx   | Throughput(bps) | AvgDelay(s)\n";
    std::cout << "-----------------------------------------------------------------------------\n";
    for (int i = 0; i < N_SOURCES; ++i) {
        double throughput = (total_time > 0) ? (source_metrics[i].bits_tx / total_time) : 0.0;
        double avg_delay = (source_metrics[i].transmitted > 0) ?
                           (source_metrics[i].delay_sum / source_metrics[i].transmitted) : 0.0;
        
        std::cout << std::setw(3) << i << " | "
                  << std::setw(5) << source_metrics[i].generated << " | "
                  << std::setw(5) << source_metrics[i].transmitted << " | "
                  << std::setw(5) << source_metrics[i].dropped << " | "
                  << std::setw(10) << source_metrics[i].bits_tx << " | "
                  << std::setw(15) << std::fixed << std::setprecision(2) << throughput << " | "
                  << std::setw(10) << std::setprecision(6) << avg_delay << "\n";
    }
    std::cout << "\n";
}

/**
 * @brief Main function to configure, run, and report on a single simulation.
 * @param type The scheduler algorithm to use (FCFS or WFQ).
 * @param file The input file name.
 */
void run_simulation(SchedulerType type, const std::string &file) {
    std::string type_str = (type == SchedulerType::FCFS) ? "FCFS" : "WFQ";
    
    if (!parse_input(file)) {
        std::cerr << "Failed to parse " << file << "\n";
        return;
    }
    reset_globals(); // Ensure clean state

    std::cout << "============================================================================\n";
    std::cout << "=== Running " << type_str << " with " << file << " ===\n";
    std::cout << "Simulation Time: " << SIM_DURATION_T << " s | Link Capacity: " << LINK_CAPACITY_C
              << " bps | Buffer Size: " << BUFFER_SIZE_B
              << " | Sources: " << N_SOURCES << "\n";
    std::cout << "----------------------------------------------------------------------------\n";

    std::vector<std::thread> producers;
    simulation_running = true;
    global_start_time = std::chrono::steady_clock::now();

    // Start server thread
    std::thread server(server_thread, type);
    // Start producer threads
    for (int i = 0; i < N_SOURCES; ++i)
        producers.emplace_back(producer_thread, i, type);

    // Let the simulation run for the specified duration
    std::this_thread::sleep_for(std::chrono::duration<double>(SIM_DURATION_T));
    simulation_running = false; // Signal threads to stop generating

    // Wait for all threads to finish
    server.join();
    for (auto &t : producers) t.join();

    double total_time = std::chrono::duration<double>(std::chrono::steady_clock::now() - global_start_time).count();
    // Ensure total_time is at least the simulation duration
    if (total_time < SIM_DURATION_T) total_time = SIM_DURATION_T; 

    // --- Calculate Final Metrics ---
    double utilization = (LINK_CAPACITY_C > 0) ? 
        ((double)total_bits_transmitted_global / (LINK_CAPACITY_C * total_time)) : 0.0;
    
    double avg_delay = (total_packets_transmitted == 0) ? 0.0 : total_delay / total_packets_transmitted;
    
    double drop_prob = (total_packets_generated == 0) ? 0.0 :
        (double)total_packets_dropped / total_packets_generated;
        
    double fairness = calculate_fairness_index();

    std::cout << "--- Overall Metrics ---\n";
    std::cout << std::fixed << std::setprecision(6)
              << "Server Utilization: " << utilization
              << " | Fairness Index: " << fairness << "\n"
              << "Average Packet Delay: " << avg_delay << " s"
              << " | Packet Drop Prob: " << drop_prob << "\n"
              << "Total Packets Tx: " << total_packets_transmitted
              << " | Total Dropped: " << total_packets_dropped
              << " | Total Bits Tx: " << total_bits_transmitted_global << "\n\n";

    print_per_source_stats(total_time);
    std::cout << "============================================================================\n\n";
}

/**
 * @brief Creates the two input files (input_A.txt and input_B.txt) as specified.
 */
void create_input_files() {
    std::ofstream ofs_a("input_A.txt");
    ofs_a << "N=4 T=1200 C=100000 B=150\n"
          << "15 800,1600 5 0.05 0.85\n"
          << "25 600,1400 3 0.03 0.80\n"
          << "30 900,1700 2 0.02 0.90\n"
          << "60 1200,2000 1 0.01 0.95\n";
    ofs_a.close();

    std::ofstream ofs_b("input_B.txt");
    ofs_b << "N=4 T=1000 C=80000 B=120\n"
          << "20 500,1500 4 0.00 0.80\n"
          << "35 700,1400 3 0.10 0.85\n"
          << "25 900,1800 2 0.05 0.90\n"
          << "50 1000,2000 1 0.15 0.95\n";
    ofs_b.close();
}

/**
 * @brief Main entry point. Creates input files and runs all 4 simulation scenarios.
 */
int main() {
    create_input_files();
    
    run_simulation(SchedulerType::FCFS, "input_A.txt");
    run_simulation(SchedulerType::WFQ, "input_A.txt");
    
    // run_simulation(SchedulerType::FCFS, "input_B.txt");
    // run_simulation(SchedulerType::WFQ, "input_B.txt");
    
    return 0;
}
